= TrainTimetableDisplay Library for Arduino =

This library is used to display a train timetable on a 0.96" TFT.
It provides one header line and 7 timetable entry lines. 

For more information about this library please visit us at
https://www.youtube.com/watch?v=JH6w2nmORbM
https://www.youtube.com/MarkusNTrains

== License ==

Copyright (c) Arduino LLC. All right reserved.
Copyright (c) Enrico Gueli. All right reserved.
Copyright (c) 2012, Adafruit Industries. All rights reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
